version: "3.9"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ci-akademik
    container_name: ci-akademik
    restart: unless-stopped
    volumes:
        - ./:/var/www/html
        - ./docker-config/nginx.conf:/etc/nginx/nginx.conf
        - ./docker-config/php.ini:/etc/php7/conf.d/custom.ini
    networks:
        - docker_main
    ports:
        - 8883:8080

networks:
  docker_main:
    name: docker_main